version: '2'

################################################################################
# Make sure to keep this file in sync with the starbelly-dev/docker-compose.yml.
################################################################################

volumes:
  db_data: {}
  web_tls: {}

services:
  app:
    image: starbelly-app
    container_name: starbelly_app
    # Allow some extra time for the crawler to finish downloads and cleanup
    # when stopping the container.
    stop_grace_period: 1m

  db:
    image: rethinkdb:2.3
    container_name: starbelly_db
    volumes:
      - db_data:/data

  web:
    image: starbelly-web
    container_name: starbelly_web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot-webroot:/certbot-webroot
      - web_tls:/etc/nginx/tls
