version: '3'

################################################################################
# Make sure to keep this file in sync with the starbelly/docker-compose.yml.
################################################################################

volumes:
  db_data: {}
  web_tls: {}

services:
  app:
    image: starbelly-dev-app
    container_name: starbelly-dev-app
    environment:
      PYTHONASYNCIODEBUG: 1
    ports:
      - 127.0.0.1:8000:8000 # Dev server
      - 127.0.0.1:8001:8888 # Jupyter notebook
    volumes:
      - ../../starbelly:/starbelly
    command: >
      python3.6 -m starbelly
                --ip 0.0.0.0
                --log-level info
                --asyncio-log /var/log/starbelly-asyncio.log
                --error-log /var/log/starbelly-error.log
                --reload
    # Allow some extra time for the crawler to finish downloads and cleanup
    # when stopping the container.
    stop_grace_period: 1m

  db:
    image: rethinkdb:2.3.6
    container_name: starbelly-dev-db
    ports:
      - 127.0.0.1:8002:8080 # RethinkDB GUI
    volumes:
      - db_data:/data

  web:
    image: starbelly-dev-web
    container_name: starbelly-dev-web
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8003:8080 # Pub Dev Server
    volumes:
      - /var/cache/pub:/var/cache/pub
      - web_tls:/etc/nginx/tls
      - ../../ng_fontawesome:/ng_fontawesome
      - ../../ng_modular_admin:/ng_modular_admin
      - ../../starbelly-web-client:/starbelly-web-client
