version: '2'

volumes:
  db_data: {}
  web_tls: {}

services:
  app:
    image: hyperiongray/starbelly-app:0.0.1
    container_name: starbelly-dev-app
    environment:
      PYTHONASYNCIODEBUG: 1
    ports:
      - 8000:8000
    volumes:
      - ../../starbelly:/starbelly
    command:
      python3 -m starbelly --ip 0.0.0.0 --reload

  db:
    image: rethinkdb:2.3
    container_name: starbelly-dev-db
    ports:
      - 8080:8080
    volumes:
      - db_data:/data

  web:
    image: starbelly-dev-web
    container_name: starbelly-dev-web
    ports:
      - 80:80
      - 443:443
      - 8001:8001
    volumes:
      - ../../starbelly-web-client:/starbelly-web-client
      - /var/cache/pub:/var/cache/pub
      - web_tls:/etc/nginx/tls
      - ../../ng2_modular_admin:/ng2_modular_admin
