FROM hyperiongray/starbelly-app:1.1.0

# Install tools that are helpful for development.
RUN apt-get install -y vim
RUN pip3 install jupyter sphinx sphinx_rtd_theme

ENV PS1='starbelly-dev-app:$PWD# '
